source 'https://rubygems.org'

gem 'jdbc-sqlite3', '~> 3.8', :platform=>:jruby
gem 'json', '~> 2.0'
gem 'sinatra', '>= 2.0.0.beta2', '< 3'
gem 'sinatra-contrib', '>= 2.0.0.beta2', '< 3'
gem 'sinja',
  git: 'https://github.com/mwpastore/sinja.git', branch: 'master'
gem 'sinja-sequel',
  git: 'https://github.com/mwpastore/sinja-sequel.git', branch: 'master'
gem 'sqlite3', '~> 1.3', :platform=>[:ruby, :mswin]
